import Link from 'next/link'
import './globals.css'
import { Bitter, Inter, Oswald } from 'next/font/google'
import SideBar from './components/Sidebar'
import { useLocale } from 'next-intl'
import { notFound } from 'next/navigation'

const inter = Inter({ subsets: ['latin', 'cyrillic'] })

export const oswald = Oswald({ subsets: ['latin', 'cyrillic'] })
export const bitter = Bitter({ subsets: ['latin', 'cyrillic'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode
    params: any
}) {
    const locale = useLocale()

    if (params.locale !== locale) {
        notFound()
    }

    return (
        <html lang={locale} className={inter.className}>
            <body className='antialiased max-w-4xl mb-40 flex flex-col md:flex-row mx-6 mt-8 md:mt-20 lg:mt-32 lg:mx-auto'>
                <SideBar />
                {children}
            </body>
        </html>
    )
}
