import Link from 'next/link'
import './globals.css'
import { Bitter, Inter, Oswald } from 'next/font/google'
import SideBar from './components/Sidebar'
import { useLocale, useTranslations } from 'next-intl'
import { notFound } from 'next/navigation'
import LocaleSwitcherSelect from './components/LocaleSwitcherSelect'

const inter = Inter({ subsets: ['latin', 'cyrillic'] })

export const oswald = Oswald({ subsets: ['latin', 'cyrillic'] })
export const bitter = Bitter({ subsets: ['latin', 'cyrillic'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode
    params: any
}) {
    const locale = useLocale()
    const t = useTranslations('LocaleSwitcher')
    const translate = useTranslations('Index')

    if (params.locale !== locale) {
        notFound()
    }
    return (
        <html lang={locale} className={inter.className}>
            <body className='bg-neutral-900 antialiased max-w-5xl mb-40 flex flex-col items-start md:flex-row mx-6 mt-8 md:mt-20 lg:mt-32 lg:mx-auto'>
                <div>
                    <aside className='md:sticky md:top-10 mb-4 md:mb-0 md:w-[150px] md:flex-shrink-0 -mx-4 md:mx-0 md:px-0 font-serif'>
                        <LocaleSwitcherSelect
                            defaultValue={locale}
                            label={t('label')}
                        >
                            {['ru', 'en'].map(element => (
                                <option
                                    className='bg-neutral-900'
                                    key={element}
                                    value={element}
                                >
                                    {t('locale', { locale: element })}
                                </option>
                            ))}
                        </LocaleSwitcherSelect>
                        <SideBar
                            locale={locale}
                            headerLink_1={translate('header_link1')}
                            headerLink_2={translate('header_link2')}
                            headerLink_3={translate('header_link3')}
                            headerLink_4={translate('header_link4')}
                        />
                    </aside>
                </div>
                {children}
            </body>
        </html>
    )
}
